---
services:
  discord_bot_paimon:
    build: ./
    container_name: discord_bot_paimon
    restart: unless-stopped
    command: "nodemon bot.js"
    volumes:
      - ./:/home/ubuntu/paimon/
      - /home/ubuntu/paimon/node_modules
    networks:
      - docker_swag

  discord_bot_paimon_db:
    image: mongo
    container_name: discord_bot_paimon_db
    restart: unless-stopped
    ports:
      - 27020:27017
    volumes:
      - ./mongodb/config/mongod.conf.orig:/etc/mongod.conf.orig
      - ./mongodb/db/:/data/db
      - ./mongodb/config/init-scripts/init-db.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=root-db
    env_file:
      - .env
    networks:
      - docker_swag

networks:
  docker_swag:
    external: true
